# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.45.0"
"rocks-config.nvim" = "3.1.1"
"oil.nvim" = "2.15.0"
# tree-sitter-c = "scm"
# tree-sitter-markdown = "scm"
"nightfox.nvim" = "3.10.0"
# nvim-treesitter-textobjects = "scm"
"rocks-dev.nvim" = "1.8.0"
"rocks-git.nvim" = "2.5.3"
luasnip = "2.4.0"
# cmp_luasnip = "scm"
"telescope.nvim" = "scm"
# tree-sitter-julia = "scm"
# tree-sitter-nix = "scm"
# "image.nvim" = "1.3.0"
semver = "1.2.1"
# nvim-treesitter-legacy-api = "0.9.2"
# tree-sitter-toml = "scm"
"telescope-ui-select.nvim" = "scm"
tree-sitter-julia = "0.0.43"
tree-sitter-markdown = "0.0.44"
tree-sitter-c = "0.0.44"
tree-sitter-yaml = "0.0.36"
tree-sitter-python = "0.0.46"
tree-sitter-markdown_inline = "0.0.42"
tree-sitter-toml = "0.0.31"
nvim-lspconfig = "2.3.0"
# tree-sitter-python = "scm"
# tree-sitter-latex = "scm"
# cmp-buffer = "scm"
# cmp-nvim-lsp = "scm"
# tree-sitter-glimmer = "0.0.29"

# nvim-smuggler = "0.5"

[plugins."lsp_lines.nvim"]
git = "https://git.sr.ht/~whynothugo/lsp_lines.nvim"
rev = "v3.0.0"

# [plugins.cmp-latex-symbols]
# git = "kdheepak/cmp-latex-symbols"
# rev = "165fb66afdbd016eaa1570e41672c4c557b57124"

# [plugins.cmp-emoji]
# git = "hrsh7th/cmp-emoji"
# rev = "e8398e2adf512a03bb4e1728ca017ffeac670a9f"

# [plugins.friendly-snippets]
# git = "rafamadriz/friendly-snippets"
# rev = "00ebcaa159e817150bd83bfe2d51fa3b3377d5c4"

[plugins.vim-fugitive]
git = "tpope/vim-fugitive"
rev = "v3.7"

[plugins."hex.nvim"]
git = "raafatturki/hex.nvim"
rev = "fcff75fcf43b5a6c5b471eed65b3a06c412d6020"

[plugins.nvim-smuggler]
git = "klafyvel/nvim-smuggler"
rev = "v0.5.0"

[plugins."blink.compat"]
git = "saghen/blink.compat"
rev = "v2.5.0"

# [plugins.cmp-latex]
# git = "https://gitlab.com/expandingman/cmp-latex.git"
# rev = "10e4a6534bbf5e87aa97cf5ae0a4ec9c207fb1e3"

[plugins.blink-cmp-latex]
git = "erooke/blink-cmp-latex"
rev = "3a958361e275bb5996e8393e7b2595b2f40c15ca"

[plugins."blink.cmp"]
git = "saghen/blink.cmp"
rev = "v1.4.1"

[plugins.undotree]
git = "mbbill/undotree"
rev = "15d91b0afe04ea9ba5cd53e30190d1602af9a925"

[bundles.cmp]
items = [
    "blink.cmp",
    "blink-cmp-latex"
]


[config]
auto_setup=true
colorscheme="nightfox"
plugin_dir = "plugins/"
